// <auto-generated/>
#pragma warning disable CS0618
using ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Chartdetails;
using ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Metadata;
using ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Ocimetadata;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\applications\{applicationMetadataName-id}\revisions\{revision}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRevisionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chartdetails property</summary>
        public global::ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Chartdetails.ChartdetailsRequestBuilder Chartdetails
        {
            get => new global::ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Chartdetails.ChartdetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ocimetadata property</summary>
        public global::ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Ocimetadata.OcimetadataRequestBuilder Ocimetadata
        {
            get => new global::ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.Ocimetadata.OcimetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.WithRevisionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRevisionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/applications/{applicationMetadataName%2Did}/revisions/{revision}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Api.V1.Applications.Item.Revisions.Item.WithRevisionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRevisionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/applications/{applicationMetadataName%2Did}/revisions/{revision}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
