// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArgoCD.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectDetailedProjectsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The clusters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ArgoCD.Sdk.Models.V1alpha1Cluster>? Clusters { get; set; }
#nullable restore
#else
        public List<global::ArgoCD.Sdk.Models.V1alpha1Cluster> Clusters { get; set; }
#endif
        /// <summary>The globalProjects property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ArgoCD.Sdk.Models.V1alpha1AppProject>? GlobalProjects { get; set; }
#nullable restore
#else
        public List<global::ArgoCD.Sdk.Models.V1alpha1AppProject> GlobalProjects { get; set; }
#endif
        /// <summary>The project property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1AppProject? Project { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1AppProject Project { get; set; }
#endif
        /// <summary>The repositories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ArgoCD.Sdk.Models.V1alpha1Repository>? Repositories { get; set; }
#nullable restore
#else
        public List<global::ArgoCD.Sdk.Models.V1alpha1Repository> Repositories { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Models.ProjectDetailedProjectsResponse"/> and sets the default values.
        /// </summary>
        public ProjectDetailedProjectsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.ProjectDetailedProjectsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArgoCD.Sdk.Models.ProjectDetailedProjectsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ArgoCD.Sdk.Models.ProjectDetailedProjectsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clusters", n => { Clusters = n.GetCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1Cluster>(global::ArgoCD.Sdk.Models.V1alpha1Cluster.CreateFromDiscriminatorValue)?.AsList(); } },
                { "globalProjects", n => { GlobalProjects = n.GetCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1AppProject>(global::ArgoCD.Sdk.Models.V1alpha1AppProject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "project", n => { Project = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1AppProject>(global::ArgoCD.Sdk.Models.V1alpha1AppProject.CreateFromDiscriminatorValue); } },
                { "repositories", n => { Repositories = n.GetCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1Repository>(global::ArgoCD.Sdk.Models.V1alpha1Repository.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1Cluster>("clusters", Clusters);
            writer.WriteCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1AppProject>("globalProjects", GlobalProjects);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1AppProject>("project", Project);
            writer.WriteCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1Repository>("repositories", Repositories);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
