// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArgoCD.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class V1alpha1ApplicationSourceJsonnet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The extVars property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar>? ExtVars { get; set; }
#nullable restore
#else
        public List<global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar> ExtVars { get; set; }
#endif
        /// <summary>The libs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Libs { get; set; }
#nullable restore
#else
        public List<string> Libs { get; set; }
#endif
        /// <summary>The tlas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar>? Tlas { get; set; }
#nullable restore
#else
        public List<global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar> Tlas { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Models.V1alpha1ApplicationSourceJsonnet"/> and sets the default values.
        /// </summary>
        public V1alpha1ApplicationSourceJsonnet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1ApplicationSourceJsonnet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArgoCD.Sdk.Models.V1alpha1ApplicationSourceJsonnet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ArgoCD.Sdk.Models.V1alpha1ApplicationSourceJsonnet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "extVars", n => { ExtVars = n.GetCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar>(global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar.CreateFromDiscriminatorValue)?.AsList(); } },
                { "libs", n => { Libs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "tlas", n => { Tlas = n.GetCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar>(global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar>("extVars", ExtVars);
            writer.WriteCollectionOfPrimitiveValues<string>("libs", Libs);
            writer.WriteCollectionOfObjectValues<global::ArgoCD.Sdk.Models.V1alpha1JsonnetVar>("tlas", Tlas);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
