// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArgoCD.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class V1alpha1Application : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ObjectMeta is metadata that all persisted resources must have, which includes all objectsusers must create.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1ObjectMeta? Metadata { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1ObjectMeta Metadata { get; set; }
#endif
        /// <summary>The operation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1Operation? Operation { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1Operation Operation { get; set; }
#endif
        /// <summary>ApplicationSpec represents desired application state. Contains link to repository with application definition and additional parameters link definition revision.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1ApplicationSpec? Spec { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1ApplicationSpec Spec { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1ApplicationStatus? Status { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1ApplicationStatus Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Models.V1alpha1Application"/> and sets the default values.
        /// </summary>
        public V1alpha1Application()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1Application"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArgoCD.Sdk.Models.V1alpha1Application CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ArgoCD.Sdk.Models.V1alpha1Application();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "metadata", n => { Metadata = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1ObjectMeta>(global::ArgoCD.Sdk.Models.V1ObjectMeta.CreateFromDiscriminatorValue); } },
                { "operation", n => { Operation = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1Operation>(global::ArgoCD.Sdk.Models.V1alpha1Operation.CreateFromDiscriminatorValue); } },
                { "spec", n => { Spec = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1ApplicationSpec>(global::ArgoCD.Sdk.Models.V1alpha1ApplicationSpec.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1ApplicationStatus>(global::ArgoCD.Sdk.Models.V1alpha1ApplicationStatus.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1ObjectMeta>("metadata", Metadata);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1Operation>("operation", Operation);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1ApplicationSpec>("spec", Spec);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1ApplicationStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
