// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArgoCD.Sdk.Models
{
    /// <summary>
    /// PullRequestGeneratorBitbucket defines connection info specific to Bitbucket.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1alpha1PullRequestGeneratorBitbucket : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Bitbucket REST API URL to talk to. If blank, uses https://api.bitbucket.org/2.0.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Api { get; set; }
#nullable restore
#else
        public string Api { get; set; }
#endif
        /// <summary>BasicAuthBitbucketServer defines the username/(password or personal access token) for Basic auth.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1BasicAuthBitbucketServer? BasicAuth { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1BasicAuthBitbucketServer BasicAuth { get; set; }
#endif
        /// <summary>BearerTokenBitbucketCloud defines the Bearer token for BitBucket AppToken auth.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1BearerTokenBitbucketCloud? BearerToken { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1BearerTokenBitbucketCloud BearerToken { get; set; }
#endif
        /// <summary>Workspace to scan. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>Repo name to scan. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Repo { get; set; }
#nullable restore
#else
        public string Repo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Models.V1alpha1PullRequestGeneratorBitbucket"/> and sets the default values.
        /// </summary>
        public V1alpha1PullRequestGeneratorBitbucket()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1PullRequestGeneratorBitbucket"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArgoCD.Sdk.Models.V1alpha1PullRequestGeneratorBitbucket CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ArgoCD.Sdk.Models.V1alpha1PullRequestGeneratorBitbucket();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api", n => { Api = n.GetStringValue(); } },
                { "basicAuth", n => { BasicAuth = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1BasicAuthBitbucketServer>(global::ArgoCD.Sdk.Models.V1alpha1BasicAuthBitbucketServer.CreateFromDiscriminatorValue); } },
                { "bearerToken", n => { BearerToken = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1BearerTokenBitbucketCloud>(global::ArgoCD.Sdk.Models.V1alpha1BearerTokenBitbucketCloud.CreateFromDiscriminatorValue); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "repo", n => { Repo = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api", Api);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1BasicAuthBitbucketServer>("basicAuth", BasicAuth);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1BearerTokenBitbucketCloud>("bearerToken", BearerToken);
            writer.WriteStringValue("owner", Owner);
            writer.WriteStringValue("repo", Repo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
