// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArgoCD.Sdk.Models
{
    /// <summary>
    /// SCMProviderGeneratorGitea defines a connection info specific to Gitea.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1alpha1SCMProviderGeneratorGitea : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Scan all branches instead of just the default branch.</summary>
        public bool? AllBranches { get; set; }
        /// <summary>The Gitea URL to talk to. For example https://gitea.mydomain.com/.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Api { get; set; }
#nullable restore
#else
        public string Api { get; set; }
#endif
        /// <summary>The insecure property</summary>
        public bool? Insecure { get; set; }
        /// <summary>Gitea organization or user to scan. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>Utility struct for a reference to a secret key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1SecretRef? TokenRef { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1SecretRef TokenRef { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Models.V1alpha1SCMProviderGeneratorGitea"/> and sets the default values.
        /// </summary>
        public V1alpha1SCMProviderGeneratorGitea()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1SCMProviderGeneratorGitea"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArgoCD.Sdk.Models.V1alpha1SCMProviderGeneratorGitea CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ArgoCD.Sdk.Models.V1alpha1SCMProviderGeneratorGitea();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allBranches", n => { AllBranches = n.GetBoolValue(); } },
                { "api", n => { Api = n.GetStringValue(); } },
                { "insecure", n => { Insecure = n.GetBoolValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "tokenRef", n => { TokenRef = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1SecretRef>(global::ArgoCD.Sdk.Models.V1alpha1SecretRef.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allBranches", AllBranches);
            writer.WriteStringValue("api", Api);
            writer.WriteBoolValue("insecure", Insecure);
            writer.WriteStringValue("owner", Owner);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1SecretRef>("tokenRef", TokenRef);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
