// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArgoCD.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class V1alpha1SyncPolicy : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The automated property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1SyncPolicyAutomated? Automated { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1SyncPolicyAutomated Automated { get; set; }
#endif
        /// <summary>The managedNamespaceMetadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1ManagedNamespaceMetadata? ManagedNamespaceMetadata { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1ManagedNamespaceMetadata ManagedNamespaceMetadata { get; set; }
#endif
        /// <summary>The retry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArgoCD.Sdk.Models.V1alpha1RetryStrategy? Retry { get; set; }
#nullable restore
#else
        public global::ArgoCD.Sdk.Models.V1alpha1RetryStrategy Retry { get; set; }
#endif
        /// <summary>The syncOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SyncOptions { get; set; }
#nullable restore
#else
        public List<string> SyncOptions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Models.V1alpha1SyncPolicy"/> and sets the default values.
        /// </summary>
        public V1alpha1SyncPolicy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1SyncPolicy"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArgoCD.Sdk.Models.V1alpha1SyncPolicy CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ArgoCD.Sdk.Models.V1alpha1SyncPolicy();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "automated", n => { Automated = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1SyncPolicyAutomated>(global::ArgoCD.Sdk.Models.V1alpha1SyncPolicyAutomated.CreateFromDiscriminatorValue); } },
                { "managedNamespaceMetadata", n => { ManagedNamespaceMetadata = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1ManagedNamespaceMetadata>(global::ArgoCD.Sdk.Models.V1alpha1ManagedNamespaceMetadata.CreateFromDiscriminatorValue); } },
                { "retry", n => { Retry = n.GetObjectValue<global::ArgoCD.Sdk.Models.V1alpha1RetryStrategy>(global::ArgoCD.Sdk.Models.V1alpha1RetryStrategy.CreateFromDiscriminatorValue); } },
                { "syncOptions", n => { SyncOptions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1SyncPolicyAutomated>("automated", Automated);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1ManagedNamespaceMetadata>("managedNamespaceMetadata", ManagedNamespaceMetadata);
            writer.WriteObjectValue<global::ArgoCD.Sdk.Models.V1alpha1RetryStrategy>("retry", Retry);
            writer.WriteCollectionOfPrimitiveValues<string>("syncOptions", SyncOptions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
