// <auto-generated/>
#pragma warning disable CS0618
using ArgoCD.Sdk.Api.V1.WriteRepositories.Item;
using ArgoCD.Sdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ArgoCD.Sdk.Api.V1.WriteRepositories
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\write-repositories
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WriteRepositoriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ArgoCD.Sdk.api.v1.writeRepositories.item collection</summary>
        /// <param name="position">Repo contains the URL to the remote repository</param>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Api.V1.WriteRepositories.Item.RepoRepoItemRequestBuilder"/></returns>
        public global::ArgoCD.Sdk.Api.V1.WriteRepositories.Item.RepoRepoItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("repoRepo%2Did", position);
                return new global::ArgoCD.Sdk.Api.V1.WriteRepositories.Item.RepoRepoItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WriteRepositoriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/write-repositories{?appProject*,credsOnly*,forceRefresh*,repo*,upsert*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WriteRepositoriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/write-repositories{?appProject*,credsOnly*,forceRefresh*,repo*,upsert*}", rawUrl)
        {
        }
        /// <summary>
        /// ListWriteRepositories gets a list of all configured write repositories
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1RepositoryList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ArgoCD.Sdk.Models.RuntimeError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ArgoCD.Sdk.Models.V1alpha1RepositoryList?> GetAsync(Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ArgoCD.Sdk.Models.V1alpha1RepositoryList> GetAsync(Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::ArgoCD.Sdk.Models.RuntimeError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ArgoCD.Sdk.Models.V1alpha1RepositoryList>(requestInfo, global::ArgoCD.Sdk.Models.V1alpha1RepositoryList.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// CreateWriteRepository creates a new write repository configuration
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1Repository"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ArgoCD.Sdk.Models.RuntimeError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ArgoCD.Sdk.Models.V1alpha1Repository?> PostAsync(global::ArgoCD.Sdk.Models.V1alpha1Repository body, Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ArgoCD.Sdk.Models.V1alpha1Repository> PostAsync(global::ArgoCD.Sdk.Models.V1alpha1Repository body, Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::ArgoCD.Sdk.Models.RuntimeError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ArgoCD.Sdk.Models.V1alpha1Repository>(requestInfo, global::ArgoCD.Sdk.Models.V1alpha1Repository.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ListWriteRepositories gets a list of all configured write repositories
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// CreateWriteRepository creates a new write repository configuration
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ArgoCD.Sdk.Models.V1alpha1Repository body, Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ArgoCD.Sdk.Models.V1alpha1Repository body, Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// ListWriteRepositories gets a list of all configured write repositories
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WriteRepositoriesRequestBuilderGetQueryParameters 
        {
            /// <summary>App project for query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("appProject")]
            public string? AppProject { get; set; }
#nullable restore
#else
            [QueryParameter("appProject")]
            public string AppProject { get; set; }
#endif
            /// <summary>Whether to force a cache refresh on repo&apos;s connection state.</summary>
            [QueryParameter("forceRefresh")]
            public bool? ForceRefresh { get; set; }
            /// <summary>Repo URL for query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("repo")]
            public string? Repo { get; set; }
#nullable restore
#else
            [QueryParameter("repo")]
            public string Repo { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WriteRepositoriesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// CreateWriteRepository creates a new write repository configuration
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WriteRepositoriesRequestBuilderPostQueryParameters 
        {
            /// <summary>Whether to operate on credential set instead of repository.</summary>
            [QueryParameter("credsOnly")]
            public bool? CredsOnly { get; set; }
            /// <summary>Whether to create in upsert mode.</summary>
            [QueryParameter("upsert")]
            public bool? Upsert { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WriteRepositoriesRequestBuilderPostRequestConfiguration : RequestConfiguration<global::ArgoCD.Sdk.Api.V1.WriteRepositories.WriteRepositoriesRequestBuilder.WriteRepositoriesRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
