// <auto-generated/>
#pragma warning disable CS0618
using ArgoCD.Sdk.Api.V1.Clusters.Item;
using ArgoCD.Sdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ArgoCD.Sdk.Api.V1.Clusters
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\clusters
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClustersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ArgoCD.Sdk.api.v1.clusters.item collection</summary>
        /// <param name="position">value holds the cluster server URL or cluster name</param>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Api.V1.Clusters.Item.IdValueItemRequestBuilder"/></returns>
        public global::ArgoCD.Sdk.Api.V1.Clusters.Item.IdValueItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id%2Evalue", position);
                return new global::ArgoCD.Sdk.Api.V1.Clusters.Item.IdValueItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClustersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/clusters{?id%2Etype*,id%2Evalue*,name*,server*,upsert*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClustersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/clusters{?id%2Etype*,id%2Evalue*,name*,server*,upsert*}", rawUrl)
        {
        }
        /// <summary>
        /// List returns list of clusters
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1ClusterList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ArgoCD.Sdk.Models.RuntimeError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ArgoCD.Sdk.Models.V1alpha1ClusterList?> GetAsync(Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ArgoCD.Sdk.Models.V1alpha1ClusterList> GetAsync(Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::ArgoCD.Sdk.Models.RuntimeError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ArgoCD.Sdk.Models.V1alpha1ClusterList>(requestInfo, global::ArgoCD.Sdk.Models.V1alpha1ClusterList.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create creates a cluster
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Models.V1alpha1Cluster"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ArgoCD.Sdk.Models.RuntimeError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ArgoCD.Sdk.Models.V1alpha1Cluster?> PostAsync(global::ArgoCD.Sdk.Models.V1alpha1Cluster body, Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ArgoCD.Sdk.Models.V1alpha1Cluster> PostAsync(global::ArgoCD.Sdk.Models.V1alpha1Cluster body, Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::ArgoCD.Sdk.Models.RuntimeError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ArgoCD.Sdk.Models.V1alpha1Cluster>(requestInfo, global::ArgoCD.Sdk.Models.V1alpha1Cluster.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List returns list of clusters
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create creates a cluster
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ArgoCD.Sdk.Models.V1alpha1Cluster body, Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ArgoCD.Sdk.Models.V1alpha1Cluster body, Action<RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List returns list of clusters
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClustersRequestBuilderGetQueryParameters 
        {
            /// <summary>type is the type of the specified cluster identifier ( &quot;server&quot; - default, &quot;name&quot; ).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id%2Etype")]
            public string? IdType { get; set; }
#nullable restore
#else
            [QueryParameter("id%2Etype")]
            public string IdType { get; set; }
#endif
            /// <summary>value holds the cluster server URL or cluster name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id%2Evalue")]
            public string? IdValue { get; set; }
#nullable restore
#else
            [QueryParameter("id%2Evalue")]
            public string IdValue { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("server")]
            public string? Server { get; set; }
#nullable restore
#else
            [QueryParameter("server")]
            public string Server { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClustersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Create creates a cluster
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClustersRequestBuilderPostQueryParameters 
        {
            [QueryParameter("upsert")]
            public bool? Upsert { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ClustersRequestBuilderPostRequestConfiguration : RequestConfiguration<global::ArgoCD.Sdk.Api.V1.Clusters.ClustersRequestBuilder.ClustersRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
