// <auto-generated/>
#pragma warning disable CS0618
using ArgoCD.Sdk.Api.V1.Account.CanI.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ArgoCD.Sdk.Api.V1.Account.CanI.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\account\can-i\{resource}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResourceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ArgoCD.Sdk.api.v1.account.canI.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ArgoCD.Sdk.Api.V1.Account.CanI.Item.Item.WithActionItemRequestBuilder"/></returns>
        public global::ArgoCD.Sdk.Api.V1.Account.CanI.Item.Item.WithActionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("action", position);
                return new global::ArgoCD.Sdk.Api.V1.Account.CanI.Item.Item.WithActionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Api.V1.Account.CanI.Item.WithResourceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/account/can-i/{resource}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArgoCD.Sdk.Api.V1.Account.CanI.Item.WithResourceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/account/can-i/{resource}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
